### ISSUE TITLE
support flutter 3.10 

### ISSUE THREAD

**Issue by mdddj** [fluttercandies/pull_to_refresh_notification#32]
`dependency_overrides:`
```yaml
pull_to_refresh_notification: 
  git: 
    url: https://github.com/mdddj/pull_to_refresh_notification
```
